apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"nginx-23","namespace":"user-23"},"spec":{"containers":[{"image":"nginx","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":1,"httpGet":{"path":"/","port":"liveness-port"},"periodSeconds":10},"name":"nginx","ports":[{"containerPort":80,"name":"liveness-port"}],"readinessProbe":{"httpGet":{"port":"liveness-port"},"initialDelaySeconds":5,"periodSeconds":5},"resources":{"limits":{"cpu":"100m","memory":"100Mi"},"requests":{"cpu":"50m","memory":"50Mi"}},"startupProbe":{"failureThreshold":30,"httpGet":{"path":"/","port":"liveness-port"},"periodSeconds":10},"volumeMounts":[{"mountPath":"/usr/share/nginx/html/","name":"htmldir"}]},{"args":["while true; do printenv DUMMY_DATABASE_PASSWORD \u003e\u003e /html/index.html; sleep 10; done;"],"command":["/bin/sh","-c"],"env":[{"name":"DUMMY_DATABASE_PASSWORD","value":"admin"}],"image":"busybox","imagePullPolicy":"Always","name":"busybox","resources":{"limits":{"cpu":"100m","memory":"100Mi"},"requests":{"cpu":"50m","memory":"50Mi"}},"volumeMounts":[{"mountPath":"/html","name":"htmldir"}]}],"volumes":[{"emptyDir":{},"name":"htmldir"}]}}
    creationTimestamp: "2021-01-14T03:37:07Z"
    name: nginx-23
    namespace: user-23
    resourceVersion: "2770993"
    selfLink: /api/v1/namespaces/user-23/pods/nginx-23
    uid: a7df8d14-0747-4e4b-a51e-09cd2f5c84bc
  spec:
    containers:
    - image: nginx
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 1
        httpGet:
          path: /
          port: liveness-port
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      name: nginx
      ports:
      - containerPort: 80
        name: liveness-port
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /
          port: liveness-port
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 50m
          memory: 50Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /usr/share/nginx/html/
        name: htmldir
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-gt6n4
        readOnly: true
    - args:
      - while true; do printenv DUMMY_DATABASE_PASSWORD >> /html/index.html; sleep
        10; done;
      command:
      - /bin/sh
      - -c
      env:
      - name: DUMMY_DATABASE_PASSWORD
        value: admin
      image: busybox
      imagePullPolicy: Always
      name: busybox
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 50m
          memory: 50Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /html
        name: htmldir
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-gt6n4
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: gke-esun-lecture-1-pool-4-4303c2db-w4bd
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - emptyDir: {}
      name: htmldir
    - name: default-token-gt6n4
      secret:
        defaultMode: 420
        secretName: default-token-gt6n4
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2021-01-14T03:37:07Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2021-01-14T03:37:16Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2021-01-14T03:37:16Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2021-01-14T03:37:07Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://23c2f00f2b7196c3568e1b54bcb4be4d1b1625ba0f1bd19920e39758cc6ba6a1
      image: busybox:latest
      imageID: docker-pullable://busybox@sha256:c5439d7db88ab5423999530349d327b04279ad3161d7596d2126dfb5b02bfd1f
      lastState: {}
      name: busybox
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2021-01-14T03:37:10Z"
    - containerID: docker://0e22ce98d7ace58e869ef889eae353607c9cb65e3ed7ed0de4f1497acb30dba4
      image: nginx:latest
      imageID: docker-pullable://nginx@sha256:10b8cc432d56da8b61b070f4c7d2543a9ed17c2b23010b43af434fd40e2ca4aa
      lastState: {}
      name: nginx
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2021-01-14T03:37:09Z"
    hostIP: 10.170.0.63
    phase: Running
    podIP: 10.60.5.14
    podIPs:
    - ip: 10.60.5.14
    qosClass: Burstable
    startTime: "2021-01-14T03:37:07Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""